### ISSUE TITLE
HomeSeerSamplePlugin-VB onTriggerButtonClick error

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Sample-Plugin-VB#1]
The subject function in sample-trigger-feature.html contains the URL for the C version of the plugin

Code:
url: '/HomeSeerSamplePlugin/sample-trigger-feature.html',

It should be

Code:
url: '/HomeSeerSamplePlugin_VB/sample-trigger-feature.html',

The incorrect URL means that the sample plugin never receives the button click action

**Comment by spudwebb** [comment]
This bug has been fixed in version 1.0.2.0, sorry for the delay.
