### ISSUE TITLE
Liquid tags (non html example) not working

### ISSUE THREAD

**Issue by btb555** [HomeSeer/Sample-Plugin-VB#2]
Hi, I am using the example project "HSPI_HomeSeerSamplePlugin_VB" and trying to make sense of how to embed data into a HTML page using liquid tags.

The example provided doesn't seem to work.

![image](https://user-images.githubusercontent.com/36972957/71773588-b924ae00-2f1c-11ea-9f64-e9d66d6cf291.png)

This should call the function GetTriggerOptions but it doesn't because this function doesn't exist, GetTriggerOption does however (guessing a typo).

![image](https://user-images.githubusercontent.com/36972957/71773594-cc377e00-2f1c-11ea-8ed9-f52dbe696729.png)

The function was never being called hence the sample plugin is broken, but after using this example to understand the concept, I set about trying this approach in my own plugin.

This is my HTML code:

![image](https://user-images.githubusercontent.com/36972957/71773599-db1e3080-2f1c-11ea-9802-fc51a498f9c9.png)

This calls this function (confirmed using breakpoint / debug).

![image](https://user-images.githubusercontent.com/36972957/71773604-ebcea680-2f1c-11ea-9563-a3b6d0010383.png)

The list is populated using a pre-populated table. 'Parse' is a simple object containing the variables I wish to pass to the HTML page.

![image](https://user-images.githubusercontent.com/36972957/71773609-fb4def80-2f1c-11ea-9957-1baa1c18c9f8.png)

I have confirmed the list(of Parse) is being populated (22 items) during the page load, but nothing happens during rendering.

![image](https://user-images.githubusercontent.com/36972957/71773615-0bfe6580-2f1d-11ea-80b4-2db96ef5f56d.png)

**Comment by mwolter805** [comment]
Found that there are several liquid calls to {{plugin_function 'HomeSeerSamplePlugin' 'GetSampleSelectList' []}} or something similar. In case anyone else runs into this, the plugin name needs to be changed to HomeSeerSamplePlugin_VB.

**Comment by spudwebb** [comment]
This bug has been fixed in version 1.0.2.0, sorry for the delay.
